$:
  action: INSERT_OR_UPDATE
action: INSERT_OR_UPDATE
application:
  _: global
  $:
    display_value: Global
category: customer
comments: ""
name: sys_security_acl_role_691fac788323c3106531c4e0deaad3d6
payload:
  record_update:
    $:
      table: sys_security_acl_role
    sys_security_acl_role:
      $:
        action: INSERT_OR_UPDATE
      sys_class_name: sys_security_acl_role
      sys_created_by: admin
      sys_created_on: 2026-09-23 00:13:13
      sys_id: 691fac788323c3106531c4e0deaad3d6
      sys_mod_count: "0"
      sys_name: u_pagerduty_sync_group.u_pagerduty_sync_group_user
      sys_package:
        _: global
        $:
          display_value: Global
          source: global
      sys_policy: ""
      sys_scope:
        _: global
        $:
          display_value: Global
      sys_security_acl:
        _: e91fac788323c3106531c4e0deaad3b4
        $:
          display_value: u_pagerduty_sync_group
      sys_update_name: sys_security_acl_role_691fac788323c3106531c4e0deaad3d6
      sys_updated_by: admin
      sys_updated_on: 2026-09-23 00:13:13
      sys_user_role:
        _: 451facf08323c3106531c4e0deaad36f
        $:
          display_value: u_pagerduty_sync_group_user
          name: u_pagerduty_sync_group_user
replace_on_upgrade: "false"
sys_created_by: admin
sys_mod_count: "0"
sys_updated_by: admin
table: u_pagerduty_sync_group
target_name: u_pagerduty_sync_group.u_pagerduty_sync_group_user
type: Access Roles
update_domain: global
update_guid: ed1fac78ec23c310e1baa1abdcfbede0
update_guid_history: ed1fac78ec23c310e1baa1abdcfbede0:1928443602
view: ""
